### PR TITLE
Adjust vet and gosec complaints

### PR DESCRIPTION
**Pull request by dataclouder**
The command `make vet` was running without tags, and therefore it was ignoring most of the test files.
After adding `-tags ALL`, some complains appeared that are addressed here.

* `Makefile`
* `govcd/access_control_catalog_test.go`
* `govcd/access_control_vapp_test.go`
* `govcd/catalog_test.go`
* `govcd/common_test.go`
* `govcd/external_network_v2_test.go`
* `govcd/nsxt_firewall_group_dynamic_security_group_test.go`

The latest version of `gosec` (2.15 released today) raises several security complaints related to unsafe usage of `defer`. Such usages are fixed in this PR.

* `govcd/api_vcd.go`
* `govcd/catalog.go` 
* `govcd/media.go` 
* `govcd/nsxt_importable_switch.go`

Furthermore, the installation of `gosec` in the Github Actions worker sometimes [fails with unclear errors](https://github.com/vmware/go-vcloud-director/actions/runs/4107335176/jobs/7086703205). To help understanding the issue, we have added more debugging information to `scripts/gosec.sh`.

### CODE REVIEW

**Review by Didainius — APPROVED** [review]
Thanks!

**Review by adambarreiro — APPROVED** [review]
Thanks for the improvements!

**Review by adezxc — APPROVED** [review]
Thanks!

**Review by lvirbalas — APPROVED** [review]
Perfect. Thanks!

**Pull request merged**
