### PR TITLE
Support update of Edge configuration (except Edge Services)

### PR DESCRIPTION
**Pull request by slavaavr**
Hi there. This PR kind of related with this issue https://github.com/vmware/go-vcloud-director/issues/202
I got it how you decided to implement Edge update, however, I think this method will not be needless. What do you think of it?

### CODE REVIEW

**Comment by dataclouder** [comment]
Thanks for your contribution.
We are already in the process of implementing a full update of Edge Gateway.
Although the update function is conceptually simple, it requires extensive additional testing to make sure we are covering all the cases.

**Comment by slavaavr** [comment]
@dataclouder oh, I see. So, when do you think update function will be resealed (approximately)? And what I have to do with this PR, close it for now?

**Comment by datacharmer** [comment]
I think you can close for now. We don't have an official release date yet, although our release cycles are usually 3 to 4 months

**Comment by slavaavr** [comment]
@datacharmer, i got it. Thanks!

**Pull request closed without merging**
