### PR TITLE
Drop support for VCD 9.5 (bump API version to 32.0)

### PR DESCRIPTION
**Pull request by Didainius**
This PR does one thing - it drops support for VCD 9.5  by bumping default API version to 32.0.

### CODE REVIEW

**Comment by Didainius** [comment]
> Please remove things like this also:
> 
> ` adminOrg.client.GetSpecificApiVersionOnCondition(">= 32.0", "32.0"))`

True. I wiped some stuff.

**Comment by vbauzysvmware** [comment]
> > Please remove things like this also:
> > ` adminOrg.client.GetSpecificApiVersionOnCondition(">= 32.0", "32.0"))`
> 
> True. I wiped some stuff.

nice work.

**Comment by vbauzysvmware** [comment]
I think one more change is needed - merge from master and upgrade this
` types.OpenApiEndpointRoles: "31.0",`

**Comment by Didainius** [comment]
> I think one more change is needed - merge from master and upgrade this
> ` types.OpenApiEndpointRoles: "31.0",`

Well spotted and I think there is room for improvement in `checkOpenApiEndpointCompatibility`. Now it returns the version in the map, but if the default version is higher than "version introduced" it should default to the default version we use.

**Comment by Didainius** [comment]
> > I think one more change is needed - merge from master and upgrade this
> > ` types.OpenApiEndpointRoles: "31.0",`
> 
> Well spotted and I think there is room for improvement in `checkOpenApiEndpointCompatibility`. Now it returns the version in the map, but if the default version is higher than "version introduced" it should default to the default version we use.

Do have a look at commit 7e5e2e0. This improved on behavior of OpenAPI function `checkOpenApiEndpointCompatibility`. It will remove need of manual labour to bump versions in `endpointMinApiVersions` when we bump default system API version. cc @dataclouder , @lvirbalas

**Comment by Didainius** [comment]
Reran `make testcatalog` on VCD 9.7 and 10 after latest merge. It succeeded including the new config.

**Review by vbauzysvmware — CHANGES_REQUESTED** [review]
Validate with 10.1. Looks ok.

One thing:

now createVdcV97 and CreateVdc duplicates one another as other vDC functions

**Comment by Didainius** [comment]
> Validate with 10.1. Looks ok.
> 
> One thing:
> 
> now createVdcV97 and CreateVdc duplicates one another as other vDC functions

Not exactly duplicates. I removed createVdc, updateVdc etc, old functions.
The public wrapper functions like `CreateVdc` still leave the capability for dynamic version handling if have to introduce it back.

**Comment by vbauzysvmware** [comment]
> > Validate with 10.1. Looks ok.
> > One thing:
> > now createVdcV97 and CreateVdc duplicates one another as other vDC functions
> 
> Not exactly duplicates. I removed createVdc, updateVdc etc, old functions.
> The public wrapper functions like `CreateVdc` still leave the capability for dynamic version handling if have to introduce it back.

Missed that function is deprecated. So we will remove that and current will be latest.

**Review by vbauzysvmware — APPROVED** [review]

**Review by dataclouder — APPROVED** [review]

**Pull request merged**
