### PR TITLE
Utility scripts

### PR DESCRIPTION
**Pull request by dataclouder**
###  Add .changes folder 

Add a folder `.changes' and `scripts/make-changelog.sh` to avoid `CHANGELOG` confilcts .
This is similar to the organization of terraform-provider-vcd.
To re-assemble the CHANGELOG, use `./scripts-make-changelog.sh VERSION`.

To show how the CHANGELOG would be organized, I added the items for v2.12.0 and v2.12.1.

###  Allow staticcheck to run in GitHub Actions

The test with `staticcheck` had stopped working when we transitioned from Travis to GitHub Actions. Changing the trigger variable fixed it. I also added a skip comment for a function that is used on demand for debugging.

### CODE REVIEW

**Review by lvirbalas — COMMENTED** [review]
What are the main differences from the way we generate changelog in Terraform?
BTW, there are typos in the PR description: "terraform-prov0wider-vcd. To re-assemple"

**Comment by dataclouder** [comment]
> What are the main differences from the way we generate changelog in Terraform?
> BTW, there are typos in the PR description: "terraform-prov0wider-vcd. To re-assemple"

The main differences:
* We use a single block CHANGELOG.md that causes conflicts at almost every merge
* In terraform-provider-vcd we use headers for all items in the CHANGELOG, while in go-vcloud-director we only use "breaking changes" and improvements.

This PR aims at having both CHANGELOGs follow the same pattern.

**Review by lvirbalas — APPROVED** [review]
LGTM!

Only one thing: I see in the generated CHANGELOG extra new lines in between the groups of changes. Is the idea to reconcile them manually before the release? This could be human-error-prone.

**Comment by dataclouder** [comment]
> I see in the generated CHANGELOG extra new lines in between the groups of changes. Is the idea to reconcile them manually before the release? This could be human-error-prone.

We can make a "perfect and final" assembly tool, but it would require using something better than shell script. The goal here is to make a good-enough draft that we can adapt manually before releasing.  We have been doing the same in terraform-provider-vcd.

**Review by Didainius — APPROVED** [review]
Thanks! A brief test worked.

**Pull request merged**
