### PR TITLE
Fix edge gateway list retrieval

### PR DESCRIPTION
**Pull request by dataclouder**
Fix Issue #363
Edge gateway retrieval was cut at the first 25 items.

### CODE REVIEW

**Review by lvirbalas — COMMENTED** [review]
Why a new function as opposed to fixing the existing one to return all items?

**Comment by dataclouder** [comment]
> Why a new function as opposed to fixing the existing one to return all items?

It was a good opportunity to normalize the name with the convention that a query returning a list should be called `Query+EntityType+List`

**Review by lvirbalas — APPROVED** [review]
LGTM!

BTW, how many usages of the old function do we have in the Terraform project?

**Review by Didainius — APPROVED** [review]
Thanks

**Comment by dataclouder** [comment]
> BTW, how many usages of the old function do we have in the Terraform project?

One. And it was changed

**Pull request merged**
